# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='course_name',
            field=models.CharField(max_length=20, verbose_name='课程名称'),
        ),
    ]
