# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-24 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='乐器', max_length=20, verbose_name='课程类别'),
        ),
    ]
