# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='课程时长(分钟)'),
        ),
    ]
