# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-30 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('cg', '唱歌'), ('yq', '乐器')], default='yq', max_length=20, verbose_name='课程类别'),
        ),
    ]
