# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-22 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_used',
            field=models.BooleanField(default=0),
        ),
    ]
