# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-02-29 17:49
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191127_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_org', models.CharField(blank=True, max_length=50, null=True, verbose_name='课程机构')),
                ('name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('teacher', models.CharField(default='', max_length=10, verbose_name='讲师名称')),
                ('desc', models.CharField(max_length=300, verbose_name='课程描述')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='课程详情')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='课程标签')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=2, verbose_name='课程难度')),
                ('category', models.CharField(choices=[('cg', '唱歌'), ('yq', '乐器')], default='yq', max_length=20, verbose_name='课程类别')),
                ('learn_time', models.IntegerField(default=0, verbose_name='课程总时长(分钟)')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='封面图')),
                ('need_know', models.CharField(default='', max_length=300, verbose_name='课程须知')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='老师的话')),
                ('course', models.FileField(upload_to='teacher/add_course/%Y/%m', verbose_name='上传课程')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
