# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200301_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(default=0, verbose_name='是否为讲师'),
        ),
    ]
