# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-03-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcourse',
            name='is_add',
            field=models.BooleanField(default=0, verbose_name='是否已添加'),
        ),
    ]
